"""initial schema

Revision ID: a707fdd21362
Revises: 
Create Date: 2026-04-12 00:31:42.195161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a707fdd21362'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('Screenplay_projectId_key'), table_name='Screenplay')
    op.drop_table('Screenplay')
    op.drop_index(op.f('CreativeRiskAudit_reportId_key'), table_name='CreativeRiskAudit')
    op.drop_table('CreativeRiskAudit')
    op.drop_index(op.f('analysis_reports_createdAt_idx'), table_name='analysis_reports')
    op.drop_index(op.f('analysis_reports_predictedRating_idx'), table_name='analysis_reports')
    op.drop_index(op.f('analysis_reports_predictedRoi_idx'), table_name='analysis_reports')
    op.drop_index(op.f('analysis_reports_projectId_key'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    op.drop_table('BatchRun')
    op.drop_index(op.f('ProjectOutline_projectId_idx'), table_name='ProjectOutline')
    op.drop_table('ProjectOutline')
    op.drop_index(op.f('ProjectSnapshot_projectId_type_idx'), table_name='ProjectSnapshot')
    op.drop_index(op.f('ProjectSnapshot_projectId_type_version_key'), table_name='ProjectSnapshot')
    op.drop_table('ProjectSnapshot')
    op.drop_index(op.f('SceneTask_batchRunId_sceneNumber_key'), table_name='SceneTask')
    op.drop_table('SceneTask')
    op.drop_index(op.f('User_email_key'), table_name='User')
    op.drop_table('User')
    op.drop_table('PipelineRun')
    op.drop_index(op.f('DevelopmentContext_projectId_key'), table_name='DevelopmentContext')
    op.drop_table('DevelopmentContext')
    op.drop_index(op.f('AgentConfig_agentName_key'), table_name='AgentConfig')
    op.drop_table('AgentConfig')
    op.drop_index(op.f('CutTask_sceneTaskId_cutNumber_key'), table_name='CutTask')
    op.drop_table('CutTask')
    op.drop_table('Asset')
    op.drop_table('LoglineIdea')
    op.drop_table('Project')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Project',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PRE_PRODUCTION', 'MAIN_PRODUCTION', 'POST_PRODUCTION', 'COMPLETED', 'ARCHIVED', name='ProjectStatus'), server_default=sa.text('\'DRAFT\'::"ProjectStatus"'), autoincrement=False, nullable=False),
    sa.Column('progress', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('directionPlan', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('directionPlanPath', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('analysisData', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('storyboardImages', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Project_userId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('Project_pkey'))
    )
    op.create_table('LoglineIdea',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('genre', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('LoglineIdea_pkey'))
    )
    op.create_table('Asset',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('IMAGE', 'VIDEO', 'AUDIO', 'MODEL_3D', 'DOCUMENT', name='AssetType'), autoincrement=False, nullable=False),
    sa.Column('phase', postgresql.ENUM('PRE', 'MAIN', 'POST', name='ProductionPhase'), autoincrement=False, nullable=False),
    sa.Column('agentName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sceneNumber', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filePath', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fileName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mimeType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fileSize', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name=op.f('Asset_projectId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Asset_pkey'))
    )
    op.create_table('CutTask',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sceneTaskId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cutNumber', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REGENERATING', name='TaskStatus'), server_default=sa.text('\'QUEUED\'::"TaskStatus"'), autoincrement=False, nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('currentStep', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stepResults', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('attempt', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('errorMessage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('startedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('completedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sceneTaskId'], ['SceneTask.id'], name=op.f('CutTask_sceneTaskId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('CutTask_pkey'))
    )
    op.create_index(op.f('CutTask_sceneTaskId_cutNumber_key'), 'CutTask', ['sceneTaskId', 'cutNumber'], unique=True)
    op.create_table('AgentConfig',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('agentName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phase', postgresql.ENUM('PRE', 'MAIN', 'POST', name='ProductionPhase'), autoincrement=False, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('AgentConfig_pkey'))
    )
    op.create_index(op.f('AgentConfig_agentName_key'), 'AgentConfig', ['agentName'], unique=True)
    op.create_table('DevelopmentContext',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('genre', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('logline', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('idea', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('protagonist', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('antagonist', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('worldview', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('characters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('concept', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('architecture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('treatment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scenario', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('review', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('script', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name=op.f('DevelopmentContext_projectId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('DevelopmentContext_pkey'))
    )
    op.create_index(op.f('DevelopmentContext_projectId_key'), 'DevelopmentContext', ['projectId'], unique=True)
    op.create_table('PipelineRun',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phase', postgresql.ENUM('PRE', 'MAIN', 'POST', name='ProductionPhase'), autoincrement=False, nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('currentStep', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='RunStatus'), server_default=sa.text('\'QUEUED\'::"RunStatus"'), autoincrement=False, nullable=False),
    sa.Column('progress', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('stepResults', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('errorMessage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('startedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('completedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name=op.f('PipelineRun_projectId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PipelineRun_pkey'))
    )
    op.create_table('User',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('passwordHash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('User_pkey'))
    )
    op.create_index(op.f('User_email_key'), 'User', ['email'], unique=True)
    op.create_table('SceneTask',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('batchRunId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sceneNumber', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REGENERATING', name='TaskStatus'), server_default=sa.text('\'QUEUED\'::"TaskStatus"'), autoincrement=False, nullable=False),
    sa.Column('currentStep', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stepResults', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('attempt', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('errorMessage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('startedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('completedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['batchRunId'], ['BatchRun.id'], name=op.f('SceneTask_batchRunId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('SceneTask_pkey'))
    )
    op.create_index(op.f('SceneTask_batchRunId_sceneNumber_key'), 'SceneTask', ['batchRunId', 'sceneNumber'], unique=True)
    op.create_table('ProjectSnapshot',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name=op.f('ProjectSnapshot_projectId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ProjectSnapshot_pkey'))
    )
    op.create_index(op.f('ProjectSnapshot_projectId_type_version_key'), 'ProjectSnapshot', ['projectId', 'type', 'version'], unique=True)
    op.create_index(op.f('ProjectSnapshot_projectId_type_idx'), 'ProjectSnapshot', ['projectId', 'type'], unique=False)
    op.create_table('ProjectOutline',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('act', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sceneNumber', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'Planned'::text"), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name=op.f('ProjectOutline_projectId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ProjectOutline_pkey'))
    )
    op.create_index(op.f('ProjectOutline_projectId_idx'), 'ProjectOutline', ['projectId'], unique=False)
    op.create_table('BatchRun',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='RunStatus'), server_default=sa.text('\'QUEUED\'::"RunStatus"'), autoincrement=False, nullable=False),
    sa.Column('totalScenes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completedScenes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('progress', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('errorMessage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('startedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('completedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name=op.f('BatchRun_projectId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('BatchRun_pkey'))
    )
    op.create_table('analysis_reports',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('market', sa.TEXT(), server_default=sa.text("'hollywood'::text"), autoincrement=False, nullable=False),
    sa.Column('totalElements', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('protagonist', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('predictedRoi', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('predictedRating', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sceneCount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('characterCount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dialogueLineCount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actionLineCount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dialogueToActionRatio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('averageWordsPerDialogue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('characterNetwork', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('beatSheet', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('emotionGraph', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('predictions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('coverage', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('production', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('narrativeArc', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tropes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name=op.f('analysis_reports_projectId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('analysis_reports_pkey'))
    )
    op.create_index(op.f('analysis_reports_projectId_key'), 'analysis_reports', ['projectId'], unique=True)
    op.create_index(op.f('analysis_reports_predictedRoi_idx'), 'analysis_reports', ['predictedRoi'], unique=False)
    op.create_index(op.f('analysis_reports_predictedRating_idx'), 'analysis_reports', ['predictedRating'], unique=False)
    op.create_index(op.f('analysis_reports_createdAt_idx'), 'analysis_reports', ['createdAt'], unique=False)
    op.create_table('CreativeRiskAudit',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reportId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('divergenceIndex', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('commercialScore', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('budgetRisk', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('resourceAllocation', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('STABLE', 'CAUTION', 'CRITICAL', 'HALTED', name='RiskStatus'), server_default=sa.text('\'STABLE\'::"RiskStatus"'), autoincrement=False, nullable=False),
    sa.Column('findings', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reportId'], ['analysis_reports.id'], name=op.f('CreativeRiskAudit_reportId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('CreativeRiskAudit_pkey'))
    )
    op.create_index(op.f('CreativeRiskAudit_reportId_key'), 'CreativeRiskAudit', ['reportId'], unique=True)
    op.create_table('Screenplay',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('currentStep', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('outline', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('characters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sceneLogs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('draft', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('draftVersion', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name=op.f('Screenplay_projectId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Screenplay_pkey'))
    )
    op.create_index(op.f('Screenplay_projectId_key'), 'Screenplay', ['projectId'], unique=True)
    # ### end Alembic commands ###
