/**
 * AssetStorage — durable home for generated bytes (videos, images, audio).
 *
 * Providers return either URLs (external CDN, short TTL) or raw bytes.
 * Before handing a result to the operator or wiring it into downstream
 * pipeline nodes, we copy it to our own storage so the asset survives
 * vendor URL expiration and we control access.
 *
 * Three impls:
 *   - InMemory       — dev/tests only; bytes live in a Map
 *   - LocalFileSystem — writes to a base directory
 *   - VercelBlob      — stub; interface locked, real calls deferred
 *
 * The returned URL shape is provider-specific (file://, https://, data:).
 * Callers MUST NOT parse it — just store and serve.
 */

export interface StoredAsset {
  key: string;
  url: string;
  bytes: number;
  mime?: string;
  storedAt: number;
}

export interface PutOptions {
  /** Logical key — stable across retries. */
  key: string;
  mime?: string;
}

export interface AssetStorage {
  put(bytes: Uint8Array | ArrayBuffer, opts: PutOptions): Promise<StoredAsset>;
  get(key: string): Promise<Uint8Array | undefined>;
  getMetadata(key: string): Promise<StoredAsset | undefined>;
  delete(key: string): Promise<boolean>;
  list(prefix?: string): Promise<StoredAsset[]>;
}

export function createInMemoryAssetStorage(): AssetStorage {
  const store = new Map<string, { bytes: Uint8Array; meta: StoredAsset }>();

  return {
    async put(bytes, opts) {
      const u8 =
        bytes instanceof Uint8Array
          ? new Uint8Array(bytes)
          : new Uint8Array(bytes);
      const meta: StoredAsset = {
        key: opts.key,
        url: `memory://${opts.key}`,
        bytes: u8.byteLength,
        mime: opts.mime,
        storedAt: Date.now(),
      };
      store.set(opts.key, { bytes: u8, meta });
      return meta;
    },
    async get(key) {
      return store.get(key)?.bytes;
    },
    async getMetadata(key) {
      return store.get(key)?.meta;
    },
    async delete(key) {
      return store.delete(key);
    },
    async list(prefix = "") {
      const out: StoredAsset[] = [];
      for (const [k, v] of store.entries()) {
        if (k.startsWith(prefix)) out.push(v.meta);
      }
      return out;
    },
  };
}

export interface LocalFileStorageOptions {
  baseDir: string;
  /** URL prefix to return. Defaults to `file://{baseDir}`. */
  urlBase?: string;
}

/**
 * Local filesystem storage — writes bytes under `baseDir/<key>` and returns
 * `file://` URLs by default. Used for dev + CI. The Hub serves assets via
 * a Next.js route that reads the key back with `get()`.
 */
export function createLocalFileAssetStorage(
  opts: LocalFileStorageOptions,
): AssetStorage {
  // Lazy-load node fs to keep the package importable in non-Node contexts
  // (the in-memory impl already covers browser paths).
  const fsPromise = import("node:fs/promises");
  const pathPromise = import("node:path");

  const urlBase = opts.urlBase ?? `file://${opts.baseDir}`;

  async function keyToPath(key: string): Promise<string> {
    const path = await pathPromise;
    const safeKey = key.replace(/\.\./g, "__");
    return path.join(opts.baseDir, safeKey);
  }

  return {
    async put(bytes, putOpts) {
      const fs = await fsPromise;
      const path = await pathPromise;
      const full = await keyToPath(putOpts.key);
      await fs.mkdir(path.dirname(full), { recursive: true });
      const u8 =
        bytes instanceof Uint8Array ? new Uint8Array(bytes) : new Uint8Array(bytes);
      await fs.writeFile(full, u8);
      return {
        key: putOpts.key,
        url: `${urlBase}/${putOpts.key}`,
        bytes: u8.byteLength,
        mime: putOpts.mime,
        storedAt: Date.now(),
      };
    },
    async get(key) {
      const fs = await fsPromise;
      try {
        const buf = await fs.readFile(await keyToPath(key));
        return new Uint8Array(buf);
      } catch {
        return undefined;
      }
    },
    async getMetadata(key) {
      const fs = await fsPromise;
      try {
        const st = await fs.stat(await keyToPath(key));
        return {
          key,
          url: `${urlBase}/${key}`,
          bytes: st.size,
          storedAt: st.mtimeMs,
        };
      } catch {
        return undefined;
      }
    },
    async delete(key) {
      const fs = await fsPromise;
      try {
        await fs.unlink(await keyToPath(key));
        return true;
      } catch {
        return false;
      }
    },
    async list(prefix = "") {
      const fs = await fsPromise;
      const path = await pathPromise;
      const walk = async (dir: string, rel = ""): Promise<StoredAsset[]> => {
        let entries;
        try {
          entries = await fs.readdir(dir, { withFileTypes: true });
        } catch {
          return [];
        }
        const results: StoredAsset[] = [];
        for (const e of entries) {
          const full = path.join(dir, e.name);
          const relKey = rel ? `${rel}/${e.name}` : e.name;
          if (e.isDirectory()) {
            results.push(...(await walk(full, relKey)));
          } else if (relKey.startsWith(prefix)) {
            const st = await fs.stat(full);
            results.push({
              key: relKey,
              url: `${urlBase}/${relKey}`,
              bytes: st.size,
              storedAt: st.mtimeMs,
            });
          }
        }
        return results;
      };
      return walk(opts.baseDir);
    },
  };
}

/**
 * Vercel Blob storage stub — interface locked, wiring deferred until the
 * Hub deployment target is confirmed (plan B.8).
 *
 * TODO(wiring-sprint): verify the current @vercel/blob SDK surface at
 * https://vercel.com/docs/storage before implementing — the API has
 * changed across versions. Auth is BLOB_READ_WRITE_TOKEN env.
 *
 * For now throws a clear error so accidental imports surface early.
 */
export function createVercelBlobAssetStorage(): AssetStorage {
  const err = () =>
    new Error(
      "Vercel Blob storage is a stub. Install @vercel/blob and wire this up in a future sprint.",
    );
  return {
    async put() { throw err(); },
    async get() { throw err(); },
    async getMetadata() { throw err(); },
    async delete() { throw err(); },
    async list() { throw err(); },
  };
}
