import { ILLMProvider, LLMResponse } from './ILLMProvider';

export class MockProvider implements ILLMProvider {
  name = 'mock';

  async generateText(systemPrompt: string, userPrompt: string): Promise<LLMResponse> {
    console.log("🛠️ MockProvider: Generating dummy response...");
    
    let content = "{}";

    if (systemPrompt.includes("3-Act")) {
      content = JSON.stringify({
        beats: [
          { act: 1, name: "Inciting Incident", sceneStart: 1, sceneEnd: 5, description: "Sample Start" }
        ]
      });
    } else if (systemPrompt.includes("Emotional Arc") || systemPrompt.includes("valence")) {
      content = JSON.stringify({
        scenes: [
          { sceneNumber: 1, score: 5, dominantEmotion: "Joy", explanation: "Mock joy" }
        ]
      });
    } else if (systemPrompt.includes("market intelligence")) {
      content = JSON.stringify({
        tier: "Hit",
        predictedMultiplier: 3.5,
        confidence: 0.8,
        reasoning: "Mock reasoning"
      });
    } else if (systemPrompt.includes("MPAA")) {
      content = JSON.stringify({
        rating: "PG-13",
        reasons: ["Mock violence"],
        confidence: 0.9
      });
    } else if (systemPrompt.includes("Script Coverage") || systemPrompt.includes("coverage analyst")) {
      content = JSON.stringify({
        title: "Untitled Screenplay",
        genre: "Drama",
        logline: "A mock screenplay evaluation.",
        synopsis: "This is a placeholder synopsis generated by the mock provider.",
        categories: [
          { name: "Plot Structure & Logic", score: 70, subcategories: [
            { name: "Narrative Structure Completeness", score: 72, assessment: "Follows basic three-act structure." },
            { name: "Pacing & Scene Flow", score: 68, assessment: "Adequate pacing with room for improvement." },
            { name: "Conflict Intensity", score: 70, assessment: "Moderate conflict development." },
          ]},
          { name: "Character & Dialogue", score: 65, subcategories: [
            { name: "Character Arc", score: 65, assessment: "Characters show some growth." },
            { name: "Dialogue Quality & Subtext", score: 65, assessment: "Dialogue is functional but lacks subtext." },
          ]},
          { name: "Theme & Tone", score: 68, subcategories: [
            { name: "Theme Clarity", score: 70, assessment: "Theme is present but could be stronger." },
            { name: "Tone Consistency", score: 66, assessment: "Generally consistent tone." },
          ]},
          { name: "Market Appeal", score: 72, subcategories: [
            { name: "Genre Fit & Trend Alignment", score: 70, assessment: "Fits genre conventions." },
            { name: "Industry Benchmarking", score: 72, assessment: "Comparable to mid-tier releases." },
            { name: "Rating Appropriateness", score: 74, assessment: "Content level appropriate for target audience." },
          ]},
          { name: "Production Feasibility", score: 75, subcategories: [
            { name: "Budget & Resource Viability", score: 75, assessment: "Production requirements are reasonable." },
          ]},
        ],
        overallScore: 70,
        verdict: "Consider",
        strengths: ["Solid premise", "Clear genre identity", "Manageable production scope"],
        weaknesses: ["Character depth needs work", "Dialogue lacks subtext", "Pacing inconsistencies"],
        recommendation: "The screenplay shows promise with a solid structural foundation but needs further development in character depth and dialogue quality before it can be recommended for production.",
      });
    }

    return {
      provider: 'mock',
      model: 'mock-v1',
      content,
      latencyMs: 100
    };
  }
}
