import os
import json
from datetime import datetime
from pathlib import Path
from sqlalchemy.orm import Session
from typing import List, Dict, Optional

from server.models.database import Project, PipelineRun, PipelineTake
from server.core.config import settings

class BibleService:
    def __init__(self, db: Session):
        self.db = db

    async def generate_bible(self, project_id: str) -> Optional[str]:
        """
        프로젝트의 모든 산출물을 집대성한 프로덕션 바이블(Markdown) 생성
        """
        project = self.db.query(Project).filter(Project.id == project_id).first()
        if not project:
            return None

        # 1. 데이터 수집
        latest_run = self.db.query(PipelineRun)\
            .filter(PipelineRun.project_id == project_id)\
            .order_by(PipelineRun.created_at.desc())\
            .first()
        
        master_takes = self.db.query(PipelineTake)\
            .filter(PipelineTake.project_id == project_id, PipelineTake.is_master == 1)\
            .all()

        # 2. Markdown 템플릿 생성
        bible_md = self._render_markdown(project, latest_run, master_takes)

        # 3. 파일 저장
        filename = f"Bible_{project.title.replace(' ', '_')}_{project.id[:8]}.md"
        file_path = settings.BIBLES_DIR / filename
        
        settings.ensure_dirs()
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(bible_md)

        # 4. 프로젝트 상태 업데이트
        project.production_book_path = str(file_path)
        project.art_bible_status = "ready"
        self.db.commit()

        return str(file_path)

    def _render_markdown(self, project: Project, run: Optional[PipelineRun], takes: List[PipelineTake]) -> str:
        """Markdown 내용 렌더링"""
        
        now = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
        
        # 헤더 & 기본 정보
        md = f"""# 🎬 PRODUCTION BIBLE: {project.title}
> **Generated by Marionette Studio AI Pipeline**  
> **Timestamp:** {now} | **Project ID:** `{project.id}`

---

## 1. MISSION BRIEF (IDENTITY)
- **Genre:** {project.genre}
- **Logline:** {project.logline}
- **Core Idea:** {project.idea}

### 🌍 Worldview & Setting
{project.worldview or "N/A"}

---

## 2. CHARACTER & ENSEMBLE
### 👤 Protagonist
{project.protagonist or "N/A"}

### 🎭 Antagonist
{project.antagonist or "N/A"}

---

## 3. VISUAL DNA & ART DIRECTION
### 🧬 Style Pillars
```json
{json.dumps(project.visual_dna, indent=2, ensure_ascii=False) if project.visual_dna else "No DNA defined"}
```

### 🏛️ Set & Environment Concept
```json
{json.dumps(project.set_concept, indent=2, ensure_ascii=False) if project.set_concept else "No set concept defined"}
```

---

## 4. SEQUENCE BREAKDOWN (MASTER TAKES)
"""
        
        # 시퀀스/테이크 정보
        if not takes:
            md += "\n> No master takes generated yet.\n"
        else:
            for take in sorted(takes, key=lambda x: x.shot_id or ""):
                md += f"### 🎬 Shot: {take.shot_id or 'Unknown'}\n"
                md += f"- **Agent:** {take.step}\n"
                md += f"- **Engine:** {take.engine or 'AI_RENDER'}\n"
                md += f"- **SOQ Score:** `{take.soq_score or 'N/A'}`\n"
                md += f"- **Asset Path:** `{take.output_path}`\n\n"
                md += f"> {take.description or 'No description available.'}\n\n"

        # 성능 메트릭 (Phase 2 벤치마킹 연동)
        md += "\n---\n\n## 5. PERFORMANCE & INTEGRITY REPORT (SAIL)\n"
        if run and run.step_results:
            durations = [res.get("duration_sec", 0) for res in run.step_results.values() if "duration_sec" in res]
            scores = [res.get("soq_score", 0) for res in run.step_results.values() if res.get("soq_score", 0) > 0]
            
            total_duration = sum(durations)
            avg_soq = sum(scores) / len(scores) if scores else 0
            
            md += f"- **Total Time to Holly (TTH):** `{total_duration:.2f}s`\n"
            md += f"- **Average Signal of Quality (SOQ):** `{avg_soq:.1f}/100`\n"
            md += f"- **Run ID:** `{run.id}`\n"
            md += "\n### Step Breakdown\n"
            md += "| Step | Duration | SOQ | Status |\n"
            md += "| :--- | :--- | :--- | :--- |\n"
            for step, data in run.step_results.items():
                md += f"| {step} | {data.get('duration_sec', '--')}s | {data.get('soq_score', '--')} | {data.get('status', 'N/A')} |\n"
        else:
            md += "\n> No performance metrics available for the latest run.\n"

        md += f"""
---
© 2026 Marionette Studios. All rights reserved.  
*This document was autonomously generated by the Marionette Industrialization Pipeline.*
"""
        return md
